### ISSUE TITLE
AntD table doesn't wrap cell contents by default

### ISSUE THREAD

**Issue by mjlangan** [allenai/varnish-legacy#132]
The AntD table will ignore a column's `width` if any cell's contents are wider than that value--instead, the widest contents will determine the width of the column. A quick solution to this would be applying `word-break: break-all` on all `td` elements within the table.

**Comment by codeviking** [comment]
This feels like something we might want to let end users set and/or adjust themselves, but I could be wrong.

The rationale is that the effect of `break-all` is a tad unexpected, and hurts the ability to read / parse the text.

I wonder if we should consider having some sort of ellipsis method for handling overflow. @Pelagic-sky -- how do you think we should handle text that overflows it's cell in a table? Truncate, or break mid-word to ensure it wraps rather than overflows the cell?
